Fix NetworkConfigPolicyTest.ProxyConfig tests.
These tests are failing in the test environment because the test environment has an UpdateDev proxy configuration.

IsDomainIsDMIsCloudPolicyOverridesPlatformPolicy/NetworkConfigPolicyTest.ProxyConfig/0 (attempt 1 of 2) unknown 00:00.004
net\network_config_unittest.cc(306): error: Expected equality of these values:
  IsDomain() + IsDM()
    Which is: 0
  proxy_configurations.size()
    Which is: 1