Fix unit test failures.
Fixing by resetting the ConfigManager instance, otherwise it was persisting between invocations and causing the following test failures:

* IsMachineIsDomain/UATest.ShouldCheckForUpdates_SkipUpdate/*
client\ua_unittest.cc(165): error: Value of: has_skipped_update
  Actual: false
Expected: true

* IsDomain/AppAutoUpdateTest.QueueDownload_AllUpdatesDisabled_NoPolicy/*
goopdate\app_unittest.cc(474): error: Expected equality of these values:
  STATE_WAITING_TO_DOWNLOAD
    Which is: 5
  app_->state()
    Which is: 17
goopdate\app_unittest.cc(475): error: Expected equality of these values:
  ((HRESULT)0L)
    Which is: 0
  app_->error_code()
    Which is: -2147219437